# Generated by Django 5.2.15 on 2026-10-04 12:31

from django.db import migrations, models
from django.contrib.postgres.fields import ArrayField
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_issue_time_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='modules',
            field=ArrayField(models.UUIDField(), blank=True, default=list),
        ),
        migrations.AddField(
            model_name='draftissue',
            name='modules',
            field=ArrayField(models.UUIDField(), blank=True, default=list),
        ),
    ]
