# Generated by Django 5.2.15 on 2026-10-04 13:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0124_add_issue_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='cycle',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='draftissue',
            name='modules',
        ),
    ]
