# Generated by Django 5.2.15 on 2026-10-04 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0125_add_issue_cycle_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='cycle',
        ),
    ]
