# Generated by Django 5.2.15 on 2026-10-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0126_remove_issue_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='cycle',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
